github:
  features:
    # Enable issue management
    issues: true
    # Enable wiki
    wiki: true

  protected_branches:
    main:
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 3